version: "3"

services:
  composer:
    image: laravel-6_php
    cap_drop: [all]
    working_dir: /var/www/laravel-6/laravel
    entrypoint: composer
    volumes:
      - ./laravel:/var/www/laravel-6/laravel:cached
